# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

trigger: none

resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

name: $(Date:yyyyMMdd).$(Rev:r)

variables:
- name: IsPreRelease
  value: 0
- name: ReleaseVersion
  value: unset
- name: TeamName
  value: C++ Cross Platform and Cloud

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: windows-2022
      os: windows
    customBuildTags:
    - ES365AIMigrationTooling
    stages:
    - stage: stage
      jobs:
      - job: Job_1
        displayName: Build release
        templateContext:
          outputs:
          - output: pipelineArtifact
            displayName: 'Publish VSIX'
            targetPath: $(Build.ArtifactStagingDirectory)/vsix
            artifactName: vsix
          - output: pipelineArtifact
            displayName: SBOM
            targetPath: $(Build.ArtifactStagingDirectory)/_manifest
            artifactName: sbom
        steps:
        - checkout: self
          clean: true
          fetchTags: false
        - task: CmdLine@2
          displayName: Check ReleaseVersion
          inputs:
            script: |-
              @echo off
              if "$(ReleaseVersion)"=="unset" (
                  echo ^"ReleaseVersion^" was not set
                  exit /B 1
              )
              exit /b 0
        - template: /azure-pipelines/shared/build.yml@self